version: "3.0"
services:
  db:
    # logging:
    #   driver: none
    image: postgres
    hostname: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: user
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # networks:
    #   - zombie_internal
  Zombie:
    restart: always
    image: zombie-serv
    hostname: zombie_serv
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
    # networks:
    #   - zombie_internal
# networks:
#   zombie_internal:
#     internal: false